= ECMAScript Modules Cheat Sheet

////

Andy Oram: Although I edited this cheat sheet, I would really like to see it longer. Aren't there other stable features that would interest users? I checked the documentation and it was pretty long. But I also saw that most of the featuers were in the experimental stage or subject to change, so I see why we should not include them.

////

This cheat sheet introduces ECMAScript modules (ESM), an alternative to CommonJS modules for sharing JavaScript functions in Node.js.

== Exporting a module

The following code exports the module in the +funTimes.mjs+ file:

```js

function funTimes() {
  return 'Fun'
}

export { funTimes };
```

== Importing a function

The following code imports and runs the +funTimes+ function from the +funTimes.mjs+ file:

```js
import { funTimes } from './funTimes.mjs'

funTimes();
```

== Enabling ESM

Because Node.js treats code as CommonJS modules by default, module authors will need to tell Node.js to treat the code as ECMAScript Modules by either using the `.mjs` file extension (as shown in earlier examples) or by using the `type` field in the +package.json+ file:

```js
// package.json

{
  name: "funTimes",
  type: "module"
}
```

== Default exports

A default export allows a module to provide a default function:

```js
// funTimes.mjs

function funTimes() {
  return 'Fun'
}

export default funTimes;
```

Importing this default function could look something like this:

```js
// app.mjs

import funTimes from './funTimes.mjs'

funTimes();
```
