= NPM CLI -  Commands and Flags

This cheat sheet covers the most common and helpful commands and flags for the npm CLI.

// TODO: something about npm comes with node

npx
Run a command from an npm package

== Basic Usage

`-v, --version`:: Prints the current version of npm you are using
`<command> -h, --help`:: quick help on the specified command
`-l`:: display full usage info

== Create a new Node.js application

`npm init [--yes|-y|--scope]`:: Initialize a new Node.js Project,  Create a package.json file

[cols="25,75"]
|===
|`--yes, -y`
| Skip the init questionnaire

|`--scope`
| Create a scoped application/module
|===

== Install Node Modules

`npm install <module_name>`:: Installs the specifed module as a Dependency

[cols="25,75"]
|===
|`---save-dev`
| Installs the specifed module as a Development Dependecy

|`-g`
| Installs the module globally
|===


`npm install [--production]`:: Installs the modules specified in the package.json.  The `--production` flag will not install development dependencies

`npm ci`:: similar to `npm install`, but for use in automated environments such as test platforms, continuous integration, and deployment

npm uninstall
Remove a package

npm outdated
Check for outdated packages

npm update
Update a package


== NPM Scripts

`npm start`:: Run a predefined command specified in the `start` property of a package's `scripts` object.

`npm run [script]::` Run a predefined command specified in the `[script]` property of package's `scripts` object

== Publish a Node Module

== Misc

npm audit
Run a security audit

npm bugs
Bugs for a package in a web browser maybe

npm config
Manage the npm configuration files

npm docs
Docs for a package in a web browser maybe

npm fund
Retrieve funding information

npm ls
List installed packages

npm prune
Remove extraneous packages

// TODO: login to the registry?

// TODO: npm publish

// TODO: .npmrc
// target another registry

// TODO: Deprecate a module


// TODO: something around global installs or one off usage, npx

// TODO: dist-tag
// checking
// setting
// using a canary tag

// TODO: npm audit

npm dist-tag
Modify package distribution tags

npm link
Symlink a package folder



npm shrinkwrap
Lock down dependency versions for publication

npm version
Bump a package version

npm pack
Create a tarball from a package

npm publish
Publish a package

npm deprecate
Deprecate a version of a package

npm unpublish
Remove a package from the registry




npm adduser
Add a registry user account

npm logout
Log out of the registry

npm whoami
Display npm username


