= Ten Tips For Running Node.js Applications on Red Hat OpenShift

To run your Node.js applications on Red Hat OpenShift effectively, try these tips.

== 1. Don’t run as root

 - Running processes as root, even in containers, can be a security risk, particularly if external resources are mapped into the container.

 - When using Docker or Podman, you can change the user with the `USER` command. Well-designed base containers already do this, but you should always check which user is used by default.

== 2. Use UBI containers

  - UBI-based containers are already built into OpenShift, which is a benefit for your application because it doesn’t need to rely on an outside service such as Docker Hub.

  - UBI-based container images run as non-root, which ties in nicely with Tip 1.


== 3. Try to use the most minimal image you can through two-stage builds

  - Best practice is to use a two-stage build, where a larger build image is used to build an application and then the resulting artifacts are copied to a more minimal run image. The build image includes all of the tools needed to build the application (compilers, etc.), whereas the run image includes only what's needed for the application to run. The size difference between the build and run images can often be significant.


== 4. Don’t use npm start

  - Although you will often see `CMD ["npm", "start"]` in Docker files used to build Node.js applications, you should use a command like `CMD ["node","index.js"]` instead. There are a number of good reasons to avoid `npm start`:

-- One less component. You generally don't need `npm` to start your application. If you avoid using this command in the container, you will not be exposed to any security vulnerabilities that might exist in that component or its dependencies.

-- One less process. Instead of running two processes (`npm` and `node`) you run only one.

  - 'npm' can lead to issues with signals and child processes. You can read more about those problems in the https://docs.docker.com/develop/develop-images/dockerfile_best-practices/[Docker best practices documentation].

== 5. Use Health Checks

 - The first thing you need to build into your application is support for liveness and readiness endpoints. OpenShift has built-in functionality to check these endpoints:

-- Liveness: Restart the container when the liveness endpoint does not respond to indicate that the application is alive.
-- Readiness: Defer sending traffic until the application is ready to accept traffic, or step sending traffic if the application is no longer able to accept traffic.


== 6. Logging

  - Node.js developers need to know how to do logging in a cloud-native environment. In container development, writing logs out to disk does not generally make sense because of the extra steps needed to make the logs available outside the container—and they will be lost once the container is stopped.

  - Logging to standard out (`stdout`) is more appropriate for the cloud, and structured logging (for example, using JSON) is the current trend. One excellent module is https://getpino.io/[pino], a fast, structured logger for Node.js that is easy to use.


== 7. Metrics

  - In an OpenShift deployment, your application is running in containers, there may be multiple copies of each container, and it is not necessarily easy to find or query those containers in order to gather information about how your application is running. For these reasons, it is important for your container to export the key metrics you need for understanding and tracking the health of your application.

  - https://prometheus.io/[Prometheus] is the de facto standard for this task. It defines a set of metrics that you should export and gives you the ability to add additional application-specific metrics that are important to your business.


== 8. Externalize Secrets

  - Secrets should be externalized and made available to the application at runtime through secure means.

  - Using a ConfigMap can help externalize Secrets.


== 9. Don’t use privileged ports

  - Ports below 1024 are considered trusted and a process must have additional privileges to be able to bind to them.

  - If you follow Tip 1 and build your containers as non-root, your process can't bind to the privileged ports.

== 10. Setting Memory Limits

  - The Node.js runtime sets default memory limits for the heap that might not match what you want to use in production.
  - Use an environment variable in your start scripts so that you can tell the Node.js runtime in the container to use a limit high enough to accommodate the memory you provide to the container when it runs.
  - The following setting is an example of such an environment variable in the start script within `package.json`:

```
"start": "if [ -z \"$MAX_NODE_MEMORY\" ]; then export MAX_NODE_MEMORY=2048; fi; node --max-old-space-size=$MAX_NODE_MEMORY bin/app.js",
```

  - This practice allows you to configure the `max-old-space-size` to align with what you define in your Kubernetes deployment files or set with the `--memory` option in `docker run` commands.
